Fix getStreetRegexByCountry returns null when BE
myparcelnl/sdk pull request #273
Opened 2020-10-30 08:51 UTC by robindelaater

2020-10-30 09:08 UTC, RichardPerdaan approved these changes

2020-11-02 07:57 UTC, reindert-vetter requested changes

2020-11-02 07:57 UTC, reindert-vetter commented on src/Helper/ValidateStreet.php
> +        if ($localIsNl && $destinationIsBe) {
Als destination BE is, zal je nooit een belgisch adres willen opsplitsen op de nederlandse manier.

2020-11-02 07:57 UTC, reindert-vetter commented on src/Helper/ValidateStreet.php
> +        if ($localIsNl && $destinationIsBe) {
Zou je me willen vertellen wat waarom je dit doet? Ik zie een story nummer in je pr titel.

2020-11-02 07:58 UTC, reindert-vetter commented on src/Helper/ValidateStreet.php
> +        if ($localIsNl && $destinationIsBe) {
Ik denk dat bij NL -> BE het valide is dat getStreetRegexByCountry null terug geeft.

2020-11-02 11:13 UTC, closed without merging