fix: cut off longer descriptions on customs form
myparcelnl/sdk pull request #345
Opened 2021-11-23 14:00 UTC by markernst97

2021-11-24 08:59 UTC, RichardPerdaan requested changes

2021-11-24 08:59 UTC, RichardPerdaan commented on src/Model/MyParcelCustomsItem.php
> +    public const DEFAULT_DESCRIPTION_MAX_LENGTH = 30;
Deze zou je weg kunnen halen

2021-11-24 08:59 UTC, RichardPerdaan commented on src/Model/MyParcelCustomsItem.php
> +        $maxLength = self::DEFAULT_DESCRIPTION_MAX_LENGTH;
Je zou de constante van de AbstractConsignment kunnen gebruiken.

2021-11-24 13:28 UTC, RichardPerdaan approved these changes

2021-11-24 14:47 UTC, EdieLemoine requested changes

2021-11-24 14:47 UTC, EdieLemoine commented on src/Model/MyParcelCustomsItem.php
> +            $carrier   = ConsignmentFactory::createByCarrierName($carrierName);
Als je de `$carrierName` param verandert in `$carrier` (`string|int|AbstractCarrier`) en dan `ConsignmentFactory::createFromCarrier($carrier)` gebruikt maak je dit een stuk prettiger voor gebruikers, dan kan je namelijk een carrier id, naam of class(/class-string) meegeven.

2021-11-24 14:47 UTC, EdieLemoine commented on src/Model/MyParcelCustomsItem.php
> +            $description = Str::limit($description, $maxLength - 3, '...');
Je hoeft niet te checken of de string te lang is, dat doet `Str::limit` zelf

2021-11-25 08:30 UTC, RichardPerdaan submitted a review, later dismissed

2021-11-25 09:02 UTC, EdieLemoine approved these changes

2021-11-25 09:04 UTC, EdieLemoine requested changes

2021-11-25 09:04 UTC, EdieLemoine commented on src/Model/MyParcelCustomsItem.php
> +        $this->description = $description;
het is mogelijk dat description hier een int is, misschien nog even casten naar een string in deze regel zodat we nooit (meer) foute waarden in description kunnen krijgen

2021-11-25 09:05 UTC, joerivanveen requested changes

2021-11-25 09:05 UTC, joerivanveen commented on src/Model/MyParcelCustomsItem.php
> +        $description = Str::limit($description, $maxLength - 3, '...');
$description is nu overbodig geworden als variabele

2021-11-25 09:05 UTC, joerivanveen commented on src/Model/MyParcelCustomsItem.php
> +use MyParcelNL\Sdk\src\Model\Consignment\BpostConsignment;
Dubbelcheck even of je deze specifieke carrier classes nodig hebt, volgens mij niet

2021-11-26 09:38 UTC, RichardPerdaan approved these changes

2021-11-26 13:41 UTC, joerivanveen approved these changes

2021-11-29 09:31 UTC, EdieLemoine approved these changes

2021-12-08 08:05 UTC, merged