fix: export orders with a pickup location for PPS
myparcelnl/sdk pull request #346
Opened 2021-11-25 14:27 UTC by RichardPerdaan

2021-11-26 08:33 UTC, EdieLemoine requested changes

2021-11-26 08:33 UTC, EdieLemoine commented on src/Model/Fulfilment/AbstractOrder.php
> +     * Shipping address of the customer.
Deze comment klopt niet

2021-11-26 08:33 UTC, EdieLemoine commented on src/Model/PickupLocation.php
> +    public function toArray(): array
kun je deze ff formatten met mijn config (die ik je ga sturen)? dingen staan niet netjes op alfabetische volgorde

2021-11-29 13:29 UTC, joerivanveen approved these changes

2021-11-30 13:15 UTC, EdieLemoine approved these changes

2021-12-10 10:21 UTC, merged