feat(pps): add drop-off point to order
myparcelnl/sdk pull request #387
Opened 2022-01-26 12:40 UTC by markernst97

2022-01-27 09:01 UTC, joerivanveen commented on src/Model/Fulfilment/AbstractOrder.php
> +    protected $dropOffPoint;
Properties snakecase toch?

2022-01-27 09:03 UTC, joerivanveen requested changes

2022-01-27 09:03 UTC, joerivanveen commented on src/Collection/Fulfilment/OrderCollection.php
> +    private function getDropOffPoint(DropOffPoint $dropOffPoint): array
Het is (blijkbaar) de bedoeling dat in de OrderCollection de dropoffpoint als array terugkomt, dan zou ik de benaming van de method daar ook op toespitsen, nu was het in eerste instantie verwarrend.

2022-02-01 12:31 UTC, EdieLemoine approved these changes

2022-02-02 08:00 UTC, merged