fix(pps): accept null as dropoffpoint to avoid errors
myparcelnl/sdk pull request #391
Opened 2022-02-02 11:14 UTC by markernst97

2022-02-03 09:18 UTC, EdieLemoine commented on src/Collection/Fulfilment/OrderCollection.php
> +        return $dropOffPoint ? [
Waarom moet dit?

2022-02-03 12:28 UTC, EdieLemoine requested changes

2022-02-03 12:28 UTC, EdieLemoine commented on src/Collection/Fulfilment/OrderCollection.php
> +    private function getDropOffPointAsArray(DropOffPoint $dropOffPoint): ?array
```suggestion
    private function getDropOffPointAsArray(DropOffPoint $dropOffPoint): array
```

2022-02-04 09:10 UTC, RichardPerdaan approved these changes

2022-02-04 09:46 UTC, joerivanveen approved these changes

2022-02-04 09:52 UTC, merged