feat: account for pickup with shipment options
myparcelnl/sdk pull request #395
Opened 2022-02-07 16:55 UTC by joerivanveen

- fixed 2 remaining 'broken'. tests
- no test yet for the shipmentoptions / pickup functionality

2022-02-09 09:24 UTC, EdieLemoine requested changes

2022-02-09 09:24 UTC, EdieLemoine commented on src/Model/Consignment/AbstractConsignment.php
> +        $isPackage               = $this->getPackageType() === self::PACKAGE_TYPE_PACKAGE;
yoda notation

2022-02-09 09:24 UTC, EdieLemoine commented on src/Model/Consignment/AbstractConsignment.php
> +        $pickupAllowedOrNoPickup = $this->getDeliveryType() !== self::DELIVERY_TYPE_PICKUP
Deze vind ik niet nice...

2022-02-09 09:24 UTC, EdieLemoine commented on test/Model/Consignment/ConsignmentOtherOptionsTest.php
> -        self::markTestBroken();
💃🏼

2022-02-09 09:24 UTC, EdieLemoine commented on test/Helper/MyParcelCollectionTest.php
> +        $collection = $this->generateSimpleCollection(10, true);
🎉

2022-02-09 09:24 UTC, EdieLemoine commented on src/Model/Consignment/AbstractConsignment.php
> +        return [];
Kun je deze lines nog coveren? Is wel heel zonde anders

2022-02-16 15:30 UTC, markernst97 approved these changes

2022-02-17 14:50 UTC, EdieLemoine approved these changes

2022-02-18 10:26 UTC, merged