fix: allow 6 characters for number suffix
myparcelnl/sdk pull request #399
Opened 2022-02-21 09:16 UTC by markernst97

2022-02-21 09:32 UTC, EdieLemoine commented
Je tests falen, en graag een test maken/bijwerken die bevestigt dat dit werkt

2022-02-21 09:50 UTC, RichardPerdaan requested changes

2022-02-21 09:50 UTC, RichardPerdaan commented on src/Helper/ValidateStreet.php
> +        '[\-a-zA-Z]{1}[a-zA-Z\s]{0,5}'.      // starts with a letter and has up to 5 letters with a space
A-Z is niet meer nodig omdat we de `i` op het einde gebruiken

2022-02-24 15:05 UTC, joerivanveen approved these changes

2022-03-01 09:57 UTC, EdieLemoine commented
This will allow us to fix myparcelnl/woocommerce#789

2022-03-02 10:55 UTC, RichardPerdaan approved these changes

2022-03-03 08:31 UTC, merged