fix: adjust instabox shipment for ConsignmentAdapter usage
myparcelnl/sdk pull request #406
Opened 2022-03-30 13:50 UTC by markernst97

2022-03-31 14:19 UTC, joerivanveen submitted a review, later dismissed

2022-04-07 14:42 UTC, EdieLemoine requested changes

2022-04-07 14:42 UTC, EdieLemoine commented on src/Helper/MyParcelCollection.php
> +            //TODO: Make AbstractConsignmentAdapter for carrier specific exceptions (https://jira.dmp.zone/browse/MY-32524)
pas je deze nog even aan?

2022-04-11 14:31 UTC, joerivanveen approved these changes

2022-04-21 14:30 UTC, EdieLemoine approved these changes

2022-04-21 14:37 UTC, EdieLemoine approved these changes

2022-04-21 14:39 UTC, joerivanveen approved these changes

2022-05-12 14:23 UTC, merged