fix: accept empty dropoff point for postnl orders
myparcelnl/sdk pull request #407
Opened 2022-04-05 08:26 UTC by markernst97

2022-04-07 08:09 UTC, joerivanveen requested changes

2022-04-07 14:08 UTC, joerivanveen approved these changes

2022-04-07 14:33 UTC, EdieLemoine requested changes

2022-04-11 14:42 UTC, joerivanveen approved these changes

2022-04-14 08:27 UTC, EdieLemoine requested changes

2022-04-14 08:27 UTC, EdieLemoine commented on src/Model/Carrier/CarrierInstabox.php
> +    public const CONSIGNMENT             = InstaboxConsignment::class;
uitlijnen

2022-04-14 08:27 UTC, EdieLemoine commented on src/Model/Carrier/CarrierPostNL.php
> +    public const CONSIGNMENT             = PostNLConsignment::class;
uitlijnen

2022-04-14 08:27 UTC, EdieLemoine commented on src/Model/Fulfilment/AbstractOrder.php
> +            throw new Exception(
Dit moet in een Validator

2022-04-14 08:27 UTC, EdieLemoine commented on test/Bootstrap/ConsignmentTestCase.php
> +        if (CarrierInstabox::NAME === $carrier->getName()) {
Dit hoeft helemaal niet, je moet er gewoon voor zorgen dat de functie wordt aangeroepen in/door een test. nu heb je super specifieke business logic in de default test die niet nodig is. 

Dat die line niet al gecovered werd laat je eigenlijk zien dat je wat mist in je codes. Er zou een Validator Rule moeten komen op consignment en/of order die checkt of er een dropoff point is als het verplicht is.

2022-04-14 14:55 UTC, joerivanveen approved these changes

2022-04-15 08:11 UTC, merged