feat: add insurance possibilities for eu shipments
myparcelnl/sdk pull request #429
Opened 2022-11-29 14:25 UTC by Mark-Ernst

2022-11-30 09:26 UTC, wthijmen submitted a review, later dismissed

2022-12-01 08:25 UTC, joerivanveen submitted a review, later dismissed

2022-12-06 16:25 UTC, joerivanveen approved these changes

2022-12-08 08:38 UTC, EdieLemoine requested changes

2022-12-08 08:38 UTC, EdieLemoine commented on src/Model/Consignment/AbstractConsignment.php
> +        if (self::CC_BE === $cc) {
hier ook nog kijken of local dan wel NL is

2022-12-08 08:38 UTC, EdieLemoine commented on test/Model/Consignment/ConsignmentValidOptionsTest.php
> +                'expect' => [500,],
die extra komma's in de arrays mogen weg 😷

2022-12-08 09:39 UTC, joerivanveen approved these changes

2022-12-19 08:08 UTC, wthijmen approved these changes

2022-12-30 14:16 UTC, merged