feat: add all dhl carriers
myparcelnl/sdk pull request #446
Opened 2023-02-20 12:54 UTC by wthijmen

2023-02-20 13:14 UTC, Mark-Ernst approved these changes

2023-02-20 13:43 UTC, Mark-Ernst approved these changes

2023-02-20 15:08 UTC, joerivanveen requested changes

2023-02-20 15:08 UTC, joerivanveen commented on src/Model/Carrier/CarrierDHLEuroPlus.php
> +    public const TYPE        = 'b2b';
Het beste is denk ik om van 'b2c' en 'b2b' constanten te maken ergens op een logische plek.

2023-02-20 15:08 UTC, joerivanveen commented on src/Rule/Consignment/ShipmentOptionsRule.php
> +     * @param $conditional
Hi ik zou de term 'conditional'  vervangen door iets wat meer meteen zegt wat het doet, misschien 'countrySpecific' of iets beters als je nog iets beters weet?

2023-02-20 15:44 UTC, joerivanveen approved these changes

2023-02-20 16:24 UTC, EdieLemoine requested changes

2023-02-20 16:24 UTC, EdieLemoine commented on src/Model/Carrier/CarrierDHLEuroPlus.php
> +class CarrierDHLEuroPlus extends AbstractCarrier
Het heet "Europlus", niet "Euro Plus". Vergeet het ook niet hieronder in `HUMAN` aan te passen enzo :)

2023-02-20 16:24 UTC, EdieLemoine commented on src/Rule/Consignment/ShipmentOptionsRule.php
> +    public function __construct($required = null, $countrySpecific = null)
types

2023-02-20 16:24 UTC, EdieLemoine commented on src/Rule/Consignment/ShipmentOptionsRule.php
> +    private $requiredOptions;
types

2023-02-20 16:24 UTC, EdieLemoine commented on src/Rule/Consignment/ShipmentOptionsRule.php
> +        foreach ($this->countrySpecific as $country => $conditionalOption) {
dit is echt heel vies genest, altijd unhappy flow eerst

2023-02-20 16:24 UTC, EdieLemoine commented on src/Rule/Consignment/ShipmentOptionsRule.php
> +    private function validateCountrySpecific(AbstractConsignment $validationSubject): void
country specific wat? deze naam lijkt me niet duidelijk

2023-02-20 16:24 UTC, EdieLemoine commented on src/Rule/Consignment/ShipmentOptionsRule.php
> +        if (is_array($countrySpecific)) {
Vreemde naam voor een array, kun je wat beters bedenken? Geldt ook voor de bijbehorende functie

2023-02-20 16:24 UTC, EdieLemoine commented on src/Rule/Consignment/ShipmentOptionsRule.php
> +    private function validateRequired(array $options): void
noem dit dan ook `validateRequiredOptions`, geen shortcuts nemen in namen van dingen, zorgt er alleen maar voor dat het lastig is om te lezen

2023-02-20 16:24 UTC, EdieLemoine commented on src/Rule/Consignment/ShipmentOptionsRule.php
> +            if (! $options[$requiredOption]) {
unhappy flow eerst

2023-02-20 16:24 UTC, EdieLemoine commented on src/Validator/Consignment/DHLEuroPlusConsignmentValidator.php
> +            ], [
indenting is niet zo mooi

2023-02-20 16:24 UTC, EdieLemoine commented on src/Rule/Consignment/AllowSpecificCountriesRule.php
> +class AllowSpecificCountriesRule extends Rule
Ik denk dat `RestrictCountriesRule` of iets in die richting een duidelijkere naam is

2023-02-20 16:24 UTC, EdieLemoine commented on src/Rule/Consignment/AllowSpecificCountriesRule.php
> +        if (! in_array($validationSubject->getCountry(), $this->allowedCountries, true)) {
unhappy flow eerst

2023-02-24 09:25 UTC, wthijmen commented on src/Validator/Consignment/DHLForYouConsignmentValidator.php
> +                    //AbstractConsignment::SHIPMENT_OPTION_SAME_DAY_DELIVERY,
Tijdelijk uitgezet i.v.m. DHL Pilot (MY-35887) zodat same_day_delivery uitgezet kan worden vanuit de plugin.

2023-02-24 09:27 UTC, EdieLemoine requested changes

2023-02-24 09:27 UTC, EdieLemoine commented on src/Validator/Consignment/DHLForYouConsignmentValidator.php
> +                    //AbstractConsignment::SHIPMENT_OPTION_SAME_DAY_DELIVERY,
graag een comment die dit uitlegt

2023-02-24 09:27 UTC, EdieLemoine commented on src/Rule/Consignment/ShipmentOptionsRule.php
> +                $this->addError($option . ' is not allowed in ' . get_class($validationSubject));
geen concatenation

2023-02-24 09:27 UTC, EdieLemoine commented on src/Rule/Consignment/ShipmentOptionsRule.php
> +            if ($country !== $validationSubject->getCountry()){
formatting klopt niet

2023-02-24 09:32 UTC, EdieLemoine approved these changes

2023-02-24 09:41 UTC, merged