feat(consignment): add state property
myparcelnl/sdk pull request #469
Opened 2024-01-30 14:40 UTC by Mark-Ernst

INT-333

2024-01-31 11:11 UTC, EdieLemoine requested changes

2024-01-31 11:11 UTC, EdieLemoine commented on src/Model/Consignment/AbstractConsignment.php
> +    public function setState(?string $state): self
dit kan je vast wel even toevoegen aan de tests

2024-01-31 12:51 UTC, wthijmen approved these changes

2024-02-01 08:21 UTC, RichardPerdaan approved these changes

2024-02-01 08:57 UTC, merged